[workspace]
resolver = "2"

members = [
    "crates/*",
]


[workspace.package]
authors = ["SpiderOak, Inc."]
edition = "2021"
license = "UNLICENSED"
publish = false
rust-version = "1.80"


[workspace.lints.rust]
# missing_docs = "warn"
rust_2018_idioms = { level = "warn", priority = -1 }
unsafe_op_in_unsafe_fn = "warn"
unused_lifetimes = "warn"
unused_qualifications = "warn"


[workspace.lints.clippy]
cast_lossless = "warn"
cast_possible_wrap = "warn"
cast_precision_loss = "warn"
cast_sign_loss = "warn"
panic = "warn"
unsafe_derive_deserialize = "warn"
undocumented_unsafe_blocks = "warn"
unwrap_used = "warn"
wildcard_imports = "warn"


[workspace.dependencies]
