[workspace]
resolver = "2"

members = [
    "crates/*",
]


[workspace.package]
authors = ["SpiderOak, Inc."]
edition = "2021"
license = "UNLICENSED"
publish = false
rust-version = "1.80"


[workspace.lints.rust]
# missing_docs = "warn"
rust_2018_idioms = { level = "warn", priority = -1 }
unsafe_op_in_unsafe_fn = "warn"
unused_lifetimes = "warn"
unused_qualifications = "warn"


[workspace.lints.clippy]
cast_lossless = "warn"
cast_possible_wrap = "warn"
cast_precision_loss = "warn"
cast_sign_loss = "warn"
panic = "warn"
unsafe_derive_deserialize = "warn"
undocumented_unsafe_blocks = "warn"
unwrap_used = "warn"
wildcard_imports = "warn"


[workspace.dependencies]
aps-util = { git = "https://git.spideroak-inc.com/spideroak-inc/flow3-rs.git", branch = "main", features = ["alloc"] }
base58 = { git = "https://git.spideroak-inc.com/spideroak-inc/flow3-rs.git", branch = "main" }
buggy = { git = "https://git.spideroak-inc.com/spideroak-inc/flow3-rs.git", branch = "main" }
crypto = { git = "https://git.spideroak-inc.com/spideroak-inc/flow3-rs.git", branch = "main", features = ["alloc", "fs-keystore", "clone-aead", "std"] }
crypto-ffi = { git = "https://git.spideroak-inc.com/spideroak-inc/flow3-rs.git", branch = "main" }
device-ffi = { git = "https://git.spideroak-inc.com/spideroak-inc/flow3-rs.git", branch = "main" }
envelope-ffi = { git = "https://git.spideroak-inc.com/spideroak-inc/flow3-rs.git", branch = "main" }
idam-ffi = { git = "https://git.spideroak-inc.com/spideroak-inc/flow3-rs.git", branch = "main" }
perspective-ffi = { git = "https://git.spideroak-inc.com/spideroak-inc/flow3-rs.git", branch = "main" }
policy-compiler = { git = "https://git.spideroak-inc.com/spideroak-inc/flow3-rs.git", branch = "main" }
policy-ifgen = { git = "https://git.spideroak-inc.com/spideroak-inc/flow3-rs.git", branch = "main", features = ["serde"] }
policy-ifgen-build = { git = "https://git.spideroak-inc.com/spideroak-inc/flow3-rs.git", branch = "main" }
policy-lang = { git = "https://git.spideroak-inc.com/spideroak-inc/flow3-rs.git", branch = "main" }
policy-vm = { git = "https://git.spideroak-inc.com/spideroak-inc/flow3-rs.git", branch = "main", features = ["std"] }
runtime = { git = "https://git.spideroak-inc.com/spideroak-inc/flow3-rs.git", branch = "main", features = ["std", "libc"] }

aps = { git = "https://git.spideroak-inc.com/spideroak-inc/aps.git", branch = "main", features = ["posix", "std", "memory"] }

daemon = { path = "crates/daemon" }
daemon-api = { path = "crates/daemon-api" }
keygen = { path = "crates/keygen" }
transport = { path = "crates/transport" }

anyhow = { version = "1.0.86" }
ciborium = { version = "0.2" }
clap = { version = "4", features = ["derive"] }
futures-util = { version = "0.3.30" }
postcard = { version = "1", default-features = false, features = ["use-std", "heapless", "experimental-derive"] }
pretty_assertions = { version = "1.4" }
quinn = { version = "0.10.1" }
rcgen = { version = "0.12" }
rustls = { version = "0.21.11", default-features = false }
serde = "1"
serial_test = { version = "3" }
tarpc = { version = "0.34.0", features = ["unix", "serde-transport", "serde-transport-json"] }
tempfile = { version = "3.6.0" }
test-log = { version = "0.2.14", default-features = false, features = ["trace"] }
thiserror = { version = "1.0" }
tokio = { version = "1.40" }
tokio-util = { version = "0.7.12" }
tokio-retry = { version = "0.3" }
tracing = { version = "0.1.40" }
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }


[profile.dev]
opt-level = 1

[profile.release]
lto = true
opt-level = "z"
strip = true
