[workspace]
resolver = "2"

members = [
    "crates/*",
]


[workspace.package]
authors = ["SpiderOak, Inc."]
edition = "2021"
license = "UNLICENSED"
publish = false
rust-version = "1.80"


[workspace.lints.rust]
# missing_docs = "warn"
rust_2018_idioms = { level = "warn", priority = -1 }
unsafe_op_in_unsafe_fn = "warn"
unused_lifetimes = "warn"
unused_qualifications = "warn"


[workspace.lints.clippy]
cast_lossless = "warn"
cast_possible_wrap = "warn"
cast_precision_loss = "warn"
cast_sign_loss = "warn"
panic = "warn"
unsafe_derive_deserialize = "warn"
undocumented_unsafe_blocks = "warn"
unwrap_used = "warn"
wildcard_imports = "warn"


[workspace.dependencies]

anyhow = { version = "1.0.86" }
aps-util = { git = "https://git.spideroak-inc.com/spideroak-inc/flow3-rs.git", branch = "main" }
aps = { git = "https://git.spideroak-inc.com/spideroak-inc/aps.git", branch = "main" }
crypto = { git = "https://git.spideroak-inc.com/spideroak-inc/flow3-rs.git", branch = "main", features = ["alloc", "fs-keystore", "std"] }
policy-ifgen-build = { git = "https://git.spideroak-inc.com/spideroak-inc/flow3-rs.git", branch = "main" }
runtime = { git = "https://git.spideroak-inc.com/spideroak-inc/flow3-rs.git", branch = "main", features = ["std"] }

daemon = { path = "crates/daemon" }
keygen = { path = "crates/keygen" }
transport = { path = "crates/transport" }

postcard = { version = "1", default-features = false, features = ["use-std", "heapless", "experimental-derive"] }
quinn = { version = "0.10.1" }
rcgen = { version = "0.12" }
rustls = { version = "0.21.11", default-features = false }
serde = { version = "1" }
serial_test = { version = "3" }
tempfile = { version = "3.8.1" }
test-log = { version = "0.2.14", default-features = false, features = ["trace"] }
tokio = { version = "1.36", default-features = false, features = ["rt", "rt-multi-thread", "fs", "net", "macros", "io-util", "sync"] }
tokio-retry = { version = "0.3" }
tracing = { version = "0.1.40" }


[profile.dev]
opt-level = 1

[profile.release]
lto = true
opt-level = "z"
strip = true
