[package]
name = "daemon"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
rust-version.workspace = true


[lints]
workspace = true


[dependencies]
anyhow = { version = "1.0.22" }
clap = { version = "4", features = ["derive"] }
deser-hjson = { version = "2" }
pretty_assertions = { version = "1.4" }
serde = { version = "1" }
