[package]
name = "daemon"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
rust-version.workspace = true


[lints]
workspace = true


[dependencies]
policy-ifgen = { git = "https://git.spideroak-inc.com/spideroak-inc/flow3-rs.git", branch = "main" }

anyhow = { workspace = true }
clap = { version = "4", features = ["derive"] }
deser-hjson = { version = "2" }
pretty_assertions = { version = "1.4" }
serde = { workspace = true }

[build-dependencies]
policy-ifgen-build = { git = "https://git.spideroak-inc.com/spideroak-inc/flow3-rs.git", branch = "main" }
